import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ErasStack | Innovate Build Grow</title>
    <meta
      name="description"
      content="ErasStack delivers enterprise-grade software engineering and digital transformation solutions for businesses, NGOs, and government institutions. Secure, scalable, and maintainable systems."
    />
    <meta
      name="keywords"
      content="enterprise software, digital transformation, government systems, NGO solutions, software engineering, system modernization, AI solutions"
    />
    <meta name="author" content="ErasStack" />

    <!-- Open Graph / Social -->
    <meta property="og:type" content="website" />
    <meta
      property="og:title"
      content="ErasStack | Enterprise Software Engineering"
    />
    <meta
      property="og:description"
      content="Enterprise-grade software engineering and digital transformation solutions for businesses, NGOs, and government institutions."
    />
    <meta property="og:url" content="https://erasstack.com" />
    <meta
      property="og:image"
      content="https://lovable.dev/opengraph-image-p98pqg.png"
    />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@ErasStack" />
    <meta
      name="twitter:image"
      content="https://lovable.dev/opengraph-image-p98pqg.png"
    />

    <!-- Canonical -->
    <link rel="canonical" href="https://erasstack.com" />

    <!-- Preconnect to Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  </head>
<body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
